### ISSUE TITLE
issue to run application in xcode

### ISSUE THREAD

**Issue by animeshagrawal25** [ndfred/iperf-ios#36]
When i trying this code in xcode a code error IPFHelpViewController.h file is not found. how to resolve this error? and how to use c file in objective c?

**Comment by ndfred** [comment]
Is that an issue you are seeing when opening the project and compiling? We have Travis [continually building the project](https://travis-ci.com/github/ndfred/iperf-ios) so that shouldn't be an issue, but if it is sharing your build logs would be helpful. If you are looking to incorporate the source files into your own project, I don't think I'll be able to assist as that is really dependent on how you organise your project.

**Comment by ndfred** [comment]
Closing as this is more related to general Xcode projects and less to this project in particular
